<div>
    <div class="lds-dual-ring"></div>
    <div><?php echo __("Restoring the cart...");?></div>
</div>
<form id="flashy_form" class="form" action="<?= $block->getUrl('flashy/cart/restore'); ?>" method="post">
    <?php echo $block->getBlockHtml('formkey')?>
    <input type="hidden" name="id" value="<?= $block->getKey(); ?>">
    <input class="restore_button" type="submit" value="Restore">
</form>
<script>
    require(['jquery'],function(){
        jQuery(document).ready(function() {
            jQuery("#flashy_form").submit();
        });
    });
</script>