<?php
/**
 * @var $block \Flashy\Integration\Block\Tracking
 */
?>
<?php if( $block->getFlashyId() ) : ?>
	<script type="text/javascript">
		//<![CDATA[
			'use strict'; (function (a, b, c) { if (!a.flashy) { a.flashy = function () { a.flashy.event && a.flashy.event(arguments), a.flashy.queue.push(arguments) }, a.flashy.queue = []; var d = document.getElementsByTagName('script')[0], e = document.createElement(b); e.src = c, e.async = !0, d.parentNode.insertBefore(e, d) } })(window, 'script', 'https://js.flashyapp.com/thunder.js'), flashy('init', <?php echo $block->getFlashyId(); ?>);
			flashy('PageView');
			<?php
				$flashy_id = $block->getFlashyIdCookie();
				if( $block->customerIsLoggedIn() && !$flashy_id ) {
					?>
					flashy('setCustomer', {
						"email": "<?php echo base64_encode($block->getCustomerEmail()); ?>"
					});

			<?php }   ?>

			//]]>
			</script>
			<?php
			if( $block->getCart() )
			{
				$catsName = "";

				$items = json_decode($block->getCart());

				if ( count($items->content_ids) > 0 )
				{
					foreach($items->content_ids as $counter => $item)
					{
						$catsName .= $block->getProductCategoryName($item);

						if( $counter < (count($items->content_ids) - 1) )
							$catsName .= " , ";
					}

				}


			?>
	<script type="text/javascript">
			window.onload = function(){
				var flashy_categories = document.createElement('div');

				flashy_categories.id = "flashy_categories";

				flashy_categories.style.display = "none";

				flashy_categories.innerText = "<?php echo $catsName; ?>";

				document.body.append(flashy_categories);
			}
	</script>
		<?php } ?>

	<script type="text/javascript">
		//<![CDATA[
            function getFlashyCookie(cname) {
                var name = cname + "=";
                var decodedCookie = decodeURIComponent(document.cookie);
                var ca = decodedCookie.split(';');
                for(var i = 0; i <ca.length; i++) {
                    var c = ca[i];
                    while (c.charAt(0) == ' ') {
                        c = c.substring(1);
                    }
                    if (c.indexOf(name) == 0) {
                        return c.substring(name.length, c.length);
                    }
                }
                return "";
            }

            function setFlashyCookie(cname, cvalue) {
                var d = new Date();
                d.setTime(d.getTime() + (365*24*60*60*1000));
                var expires = "expires="+ d.toUTCString();
                document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
            }

            window.addEventListener('onFlashy', function() {

                function flashyCartManager() {

                    if (getFlashyCookie("flashy_cart_cache") != getFlashyCookie("flashy_cart"))
                    {
                        setFlashyCookie("flashy_cart", getFlashyCookie("flashy_cart_cache"));

                        flashyCart = JSON.parse(window.atob(getFlashyCookie("flashy_cart")));

                        if( flashyCart.value && flashyCart.value > 0 )
                            flashy('UpdateCart', flashyCart);

                        console.log("Flashy Update Cart:", flashyCart);
                    }
                };

                flashyCartManager();

                window.setInterval(function() {
                    flashyCartManager();
                }, 1200);

            });
		//]]>
	</script>
<?php endif; ?>